In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3], dtype='d')
arr

array([1., 2., 3.])

In [10]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [11]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [12]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
np.dot(np.linalg.inv(a), a)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [16]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [17]:
b = np.array([5, 3])
b

array([5, 3])

In [18]:
np.linalg.solve(a, b)

array([-7.,  6.])