In [1]:
import numpy as np

In [2]:
options = np.array(["Manzana", "Platano", "Fresa", "Naranja"])
a = np.random.choice(options, 10)
a

array(['Manzana', 'Naranja', 'Manzana', 'Naranja', 'Naranja', 'Manzana',
       'Fresa', 'Fresa', 'Fresa', 'Naranja'], dtype='<U7')

In [3]:
np.unique(a)

array(['Fresa', 'Manzana', 'Naranja'], dtype='<U7')

In [4]:
np.unique(a, return_counts=True)

(array(['Fresa', 'Manzana', 'Naranja'], dtype='<U7'), array([3, 3, 4]))

In [11]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
b = a[1:4]
b

array([2, 3, 4])

In [13]:
b[2:3] = 5
b

array([2, 3, 5])

In [14]:
a

array([ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10])

In [17]:
c = a[[1,4]]
c

array([2, 5])

In [18]:
c[0] = 11
c

array([11,  5])

In [19]:
a

array([ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10])

In [20]:
d = a[1:5].copy()
d

array([2, 3, 5, 5])

In [22]:
d[0:4] = 3
d

array([3, 3, 3, 3])

In [23]:
a

array([ 1,  2,  3,  5,  5,  6,  7,  8,  9, 10])

In [26]:
e = b[:2]
e

array([2, 3])

In [29]:
# know if b is a view or a copy
b.base is a, c.base is a, d.base is a, e.base is a, e.base is b, e.base is b.base

(True, False, False, True, False, True)