In [5]:
import numpy as np

In [6]:
mt = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
mt.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
rp = np.random.randint(0, 10, 12)
rp

array([6, 1, 5, 8, 5, 4, 8, 1, 5, 2, 4, 2])

In [10]:
rp.reshape(3, 4)

array([[6, 1, 5, 8],
       [5, 4, 8, 1],
       [5, 2, 4, 2]])

In [11]:
rp.reshape(2, 6)

array([[6, 1, 5, 8, 5, 4],
       [8, 1, 5, 2, 4, 2]])

In [14]:
print(rp)
rp[::-1]

[6 1 5 8 5 4 8 1 5 2 4 2]


array([2, 4, 2, 5, 1, 8, 4, 5, 8, 5, 1, 6])

In [15]:
mt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
ft = mt.flatten()
ft

array([1, 2, 3, 4, 5, 6, 7, 8, 9])