In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [3]:
a + b

array([[ 6,  8],
       [10, 12]])

In [4]:
a - b

array([[-4, -4],
       [-4, -4]])

In [5]:
a * b

array([[ 5, 12],
       [21, 32]])

In [6]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [8]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [10]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
np.dot(a, np.linalg.inv(a))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [14]:
c = np.array([56,12])

In [15]:
np.linalg.solve(a, c)

array([-100.,   78.])