In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
np.reshape(arr, (2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# np.reshape(arr, (2, 3), order='C') # -> C
# np.reshape(arr, (2, 3), order='F') # -> Fortran
np.reshape(arr, (2, 3), order='A') # -> Automatic (C, F)

array([[1, 2, 3],
       [4, 5, 6]])