In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 20, 10)
arr

array([12, 11, 15,  5,  3, 14, 12,  2,  6,  1])

In [4]:
mtx = arr.reshape(2, 5)
mtx

array([[12, 11, 15,  5,  3],
       [14, 12,  2,  6,  1]])

In [5]:
arr.max()

np.int64(15)

In [6]:
mtx.max()

np.int64(15)

In [8]:
mtx

array([[12, 11, 15,  5,  3],
       [14, 12,  2,  6,  1]])

In [7]:
mtx.max(1)
# Va revisando por filas

array([15, 14])

In [9]:
mtx.max(0)
# Va reisando por columnas

array([14, 12, 15,  6,  3])

In [11]:
arr, arr.argmax()
# Regresa el indice del mayor

(array([12, 11, 15,  5,  3, 14, 12,  2,  6,  1]), np.int64(2))

In [13]:
mtx, mtx.argmax(), mtx.argmax(0), mtx.argmax(1)

(array([[12, 11, 15,  5,  3],
        [14, 12,  2,  6,  1]]),
 np.int64(2),
 array([1, 1, 0, 1, 0]),
 array([2, 0]))

In [14]:
arr, arr.min(), arr.argmin()

(array([12, 11, 15,  5,  3, 14, 12,  2,  6,  1]), np.int64(1), np.int64(9))

In [15]:
mtx, mtx.min(), mtx.argmin(), mtx.argmin(0), mtx.argmin(1)

(array([[12, 11, 15,  5,  3],
        [14, 12,  2,  6,  1]]),
 np.int64(1),
 np.int64(9),
 array([0, 0, 1, 0, 1]),
 array([4, 4]))

En numpy 2.0 se quito el metodo de los array
para usarlo se debe usar desde numpy

arr.pyp() -> np.ptp(arr)

In [20]:
arr, np.ptp(arr)
# Peak to peak
# Diferencia entre el maximo y el minimo


(array([12, 11, 15,  5,  3, 14, 12,  2,  6,  1]), np.int64(14))

## Percentile
Percentile muetra el valor que esta a n porcentaje de los datos
np.percentile(arr, n)


In [23]:
arr, np.percentile(arr, 50), np.percentile(arr, 25)

(array([12, 11, 15,  5,  3, 14, 12,  2,  6,  1]),
 np.float64(8.5),
 np.float64(3.5))

In [24]:
arr2 =  np.array([7, 8, 9, 10, 11])
arr2, np.percentile(arr2, 50), np.percentile(arr2, 25)

(array([ 7,  8,  9, 10, 11]), np.float64(9.0), np.float64(8.0))

In [25]:
arr.sort()
arr

array([ 1,  2,  3,  5,  6, 11, 12, 12, 14, 15])

In [28]:
np.median(arr), np.median(mtx), np.median(mtx, 0), np.median(mtx, 1)
# La mediana de los valores

(np.float64(8.5),
 np.float64(8.5),
 array([ 6. ,  7. ,  7.5,  9.5, 10.5]),
 array([ 3., 12.]))

In [29]:
np.std(arr), np.std(mtx), np.std(mtx, 0), np.std(mtx, 1)
# std -> standard -> desviacion estandar

(np.float64(4.988987873306569),
 np.float64(4.988987873306569),
 array([5. , 5. , 4.5, 4.5, 4.5]),
 array([1.8547237 , 1.46969385]))

In [30]:
np.var(arr), np.var(mtx), np.var(mtx, 0), np.var(mtx, 1)
# var -> variance -> varianza
# std ** 2


(np.float64(24.89),
 np.float64(24.89),
 array([25.  , 25.  , 20.25, 20.25, 20.25]),
 array([3.44, 2.16]))

In [32]:
4.988987873306569 ** 2

24.890000000000004