In [2]:
import numpy as np

In [3]:
arr = np.random.randint(0, 20, 12)
arr

array([ 7,  4, 12, 11,  1, 14, 17, 10, 14, 17,  1,  3])

In [4]:
mtx = arr.reshape(3, 4)
mtx

array([[ 7,  4, 12, 11],
       [ 1, 14, 17, 10],
       [14, 17,  1,  3]])

In [5]:
arr.sort()
arr

array([ 1,  1,  3,  4,  7, 10, 11, 12, 14, 14, 17, 17])

Mediana != Media
Media: promedio
Mediana: valor que se encuentra en el centro de un conjunto de datos ordenados

In [6]:
np.ptp(arr), np.median(arr), np.std(arr), np.var(arr), np.mean(arr)

(np.int64(16),
 np.float64(10.5),
 np.float64(5.65869537378832),
 np.float64(32.020833333333336),
 np.float64(9.25))

In [11]:
# Concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
a, b

(array([[1, 2],
        [3, 4]]),
 array([5, 6]))

In [12]:
np.concatenate((a, b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [13]:
a.ndim, b.ndim

(2, 1)

In [14]:
b = np.expand_dims(b, axis=0)
b, b.ndim

(array([[5, 6]]), 2)

In [15]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [19]:
b, b.T, a

(array([[5, 6]]),
 array([[5],
        [6]]),
 array([[1, 2],
        [3, 4]]))