In [1]:
import numpy as np

In [5]:
arr = np.linspace(0, 10, 10, dtype='int8')
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10], dtype=int8)

In [7]:
ic = arr > 5
ic

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [8]:
arr[ic]
# arr[arr > 5]

array([ 6,  7,  8, 10], dtype=int8)

In [11]:
arr[(arr > 5) & (arr < 9)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10], dtype=int8)

In [12]:
arr[(arr < 5) | (arr > 7)]

array([ 0,  1,  2,  3,  4,  8, 10], dtype=int8)

In [13]:
ca = arr.copy()
ca[(ca < 5) | (ca > 7)] = 40
ca

array([40, 40, 40, 40, 40,  5,  6,  7, 40, 40], dtype=int8)

True