In [1]:
import numpy as np

In [2]:
l = [1, 2]
l * 2

[1, 2, 1, 2]

In [3]:
arr = np.arange(0, 10)
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
r = 1 / arr
r

/tmp/ipykernel_87873/311744770.py:1: RuntimeWarning: divide by zero encountered in divide
  r = 1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
r[0]

np.float64(inf)

In [10]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr / arr2

/tmp/ipykernel_87873/1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
mt = arr.reshape(2, 5)
mt

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
mt2 = arr2.reshape(2, 5)
mt2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
mt + mt2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [17]:
mt * mt2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [18]:
mt - mt2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.matmul(mt, mt2.T), np.matmul(mt.T, mt2)

(array([[ 30,  80],
        [ 80, 255]]),
 array([[25, 30, 35, 40, 45],
        [30, 37, 44, 51, 58],
        [35, 44, 53, 62, 71],
        [40, 51, 62, 73, 84],
        [45, 58, 71, 84, 97]]))

In [23]:
mt @ mt2.T, mt.T @ mt2

(array([[ 30,  80],
        [ 80, 255]]),
 array([[25, 30, 35, 40, 45],
        [30, 37, 44, 51, 58],
        [35, 44, 53, 62, 71],
        [40, 51, 62, 73, 84],
        [45, 58, 71, 84, 97]]))

In [24]:
mt ** mt2

array([[        1,         1,         4,        27,       256],
       [     3125,     46656,    823543,  16777216, 387420489]])

In [28]:
arr3 = np.arange(0, 3)
arr3

array([0, 1, 2])

In [29]:
arr3 + [1, 3, 5]

array([1, 4, 7])